// Device presets. Generated from sourced viewport research (yesviz / Chrome
// DevTools EmulatedDevices.ts / screensizechecker / BrowserStack), grouped by brand.
// width/height = portrait CSS (logical) px. dpr = devicePixelRatio.
// frame = bezel skin (cosmetic): ios-home | ios-notch | ios-island | android |
//         android-left | android-plain | tablet | none.
//
// ACCURACY TIERS: Apple, Google Pixel, flagship Samsung (S/Note/A) and OnePlus
// are viewport-DB-verified. Xiaomi/Redmi/Poco/Motorola/Oppo/Vivo/Honor/Asus,
// Nothing, and every foldable COVER screen are best-estimate from real panel
// specs (no viewport DB publishes them) — usually right to the breakpoint, DPR
// and cutout well-grounded, exact width may be a few px off. Verify on-device
// if a breakpoint sits right at the edge.

const UA = {
  ios: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Mobile/15E148 Safari/604.1",
  ipad: "Mozilla/5.0 (iPad; CPU OS 17_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Mobile/15E148 Safari/604.1",
  android: "Mozilla/5.0 (Linux; Android 14; Pixel 7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Mobile Safari/537.36",
  desktop: "",
};

const DEVICES = [
  { brand: "Apple", id: "iphone-se-2", name: "iPhone SE (2nd gen)", subtype: "phone", width: 375, height: 667, dpr: 2, frame: "ios-home", userAgent: UA.ios },
  { brand: "Apple", id: "iphone-se-3", name: "iPhone SE (3rd gen)", subtype: "phone", width: 375, height: 667, dpr: 2, frame: "ios-home", userAgent: UA.ios },
  { brand: "Apple", id: "iphone-11", name: "iPhone 11", subtype: "phone", width: 414, height: 896, dpr: 2, frame: "ios-notch", userAgent: UA.ios },
  { brand: "Apple", id: "iphone-11-pro", name: "iPhone 11 Pro", subtype: "phone", width: 375, height: 812, dpr: 3, frame: "ios-notch", userAgent: UA.ios },
  { brand: "Apple", id: "iphone-11-pro-max", name: "iPhone 11 Pro Max", subtype: "phone", width: 414, height: 896, dpr: 3, frame: "ios-notch", userAgent: UA.ios },
  { brand: "Apple", id: "iphone-12-mini", name: "iPhone 12 mini", subtype: "phone", width: 360, height: 780, dpr: 3, frame: "ios-notch", userAgent: UA.ios },
  { brand: "Apple", id: "iphone-12", name: "iPhone 12", subtype: "phone", width: 390, height: 844, dpr: 3, frame: "ios-notch", userAgent: UA.ios },
  { brand: "Apple", id: "iphone-12-pro", name: "iPhone 12 Pro", subtype: "phone", width: 390, height: 844, dpr: 3, frame: "ios-notch", userAgent: UA.ios },
  { brand: "Apple", id: "iphone-12-pro-max", name: "iPhone 12 Pro Max", subtype: "phone", width: 428, height: 926, dpr: 3, frame: "ios-notch", userAgent: UA.ios },
  { brand: "Apple", id: "iphone-13-mini", name: "iPhone 13 mini", subtype: "phone", width: 360, height: 780, dpr: 3, frame: "ios-notch", userAgent: UA.ios },
  { brand: "Apple", id: "iphone-13", name: "iPhone 13", subtype: "phone", width: 390, height: 844, dpr: 3, frame: "ios-notch", userAgent: UA.ios },
  { brand: "Apple", id: "iphone-13-pro", name: "iPhone 13 Pro", subtype: "phone", width: 390, height: 844, dpr: 3, frame: "ios-notch", userAgent: UA.ios },
  { brand: "Apple", id: "iphone-13-pro-max", name: "iPhone 13 Pro Max", subtype: "phone", width: 428, height: 926, dpr: 3, frame: "ios-notch", userAgent: UA.ios },
  { brand: "Apple", id: "iphone-14", name: "iPhone 14", subtype: "phone", width: 390, height: 844, dpr: 3, frame: "ios-notch", userAgent: UA.ios },
  { brand: "Apple", id: "iphone-14-plus", name: "iPhone 14 Plus", subtype: "phone", width: 428, height: 926, dpr: 3, frame: "ios-notch", userAgent: UA.ios },
  { brand: "Apple", id: "iphone-14-pro", name: "iPhone 14 Pro", subtype: "phone", width: 393, height: 852, dpr: 3, frame: "ios-island", userAgent: UA.ios },
  { brand: "Apple", id: "iphone-14-pro-max", name: "iPhone 14 Pro Max", subtype: "phone", width: 430, height: 932, dpr: 3, frame: "ios-island", userAgent: UA.ios },
  { brand: "Apple", id: "iphone-15", name: "iPhone 15", subtype: "phone", width: 393, height: 852, dpr: 3, frame: "ios-island", userAgent: UA.ios },
  { brand: "Apple", id: "iphone-15-plus", name: "iPhone 15 Plus", subtype: "phone", width: 430, height: 932, dpr: 3, frame: "ios-island", userAgent: UA.ios },
  { brand: "Apple", id: "iphone-15-pro", name: "iPhone 15 Pro", subtype: "phone", width: 393, height: 852, dpr: 3, frame: "ios-island", userAgent: UA.ios },
  { brand: "Apple", id: "iphone-15-pro-max", name: "iPhone 15 Pro Max", subtype: "phone", width: 430, height: 932, dpr: 3, frame: "ios-island", userAgent: UA.ios },
  { brand: "Apple", id: "iphone-16", name: "iPhone 16", subtype: "phone", width: 393, height: 852, dpr: 3, frame: "ios-island", userAgent: UA.ios },
  { brand: "Apple", id: "iphone-16-plus", name: "iPhone 16 Plus", subtype: "phone", width: 430, height: 932, dpr: 3, frame: "ios-island", userAgent: UA.ios },
  { brand: "Apple", id: "iphone-16-pro", name: "iPhone 16 Pro", subtype: "phone", width: 402, height: 874, dpr: 3, frame: "ios-island", userAgent: UA.ios },
  { brand: "Apple", id: "iphone-16-pro-max", name: "iPhone 16 Pro Max", subtype: "phone", width: 440, height: 956, dpr: 3, frame: "ios-island", userAgent: UA.ios },
  { brand: "Apple", id: "iphone-16e", name: "iPhone 16e", subtype: "phone", width: 390, height: 844, dpr: 3, frame: "ios-notch", userAgent: UA.ios },
  { brand: "Apple", id: "ipad-10", name: "iPad (10th gen)", subtype: "tablet", width: 820, height: 1180, dpr: 2, frame: "tablet", userAgent: UA.ipad },
  { brand: "Apple", id: "ipad-mini-6", name: "iPad mini 6", subtype: "tablet", width: 744, height: 1133, dpr: 2, frame: "tablet", userAgent: UA.ipad },
  { brand: "Apple", id: "ipad-mini-a17", name: "iPad mini (A17 Pro)", subtype: "tablet", width: 744, height: 1133, dpr: 2, frame: "tablet", userAgent: UA.ipad },
  { brand: "Apple", id: "ipad-air-11-m2", name: "iPad Air 11\" (M2)", subtype: "tablet", width: 820, height: 1180, dpr: 2, frame: "tablet", userAgent: UA.ipad },
  { brand: "Apple", id: "ipad-air-13-m2", name: "iPad Air 13\" (M2)", subtype: "tablet", width: 1024, height: 1366, dpr: 2, frame: "tablet", userAgent: UA.ipad },
  { brand: "Apple", id: "ipad-pro-11-m4", name: "iPad Pro 11\" (M4)", subtype: "tablet", width: 834, height: 1194, dpr: 2, frame: "tablet", userAgent: UA.ipad },
  { brand: "Apple", id: "ipad-pro-13-m4", name: "iPad Pro 13\" (M4)", subtype: "tablet", width: 1032, height: 1376, dpr: 2, frame: "tablet", userAgent: UA.ipad },
  { brand: "Samsung", id: "galaxy-s20", name: "Galaxy S20", subtype: "phone", width: 360, height: 800, dpr: 4, frame: "android", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-s20-plus", name: "Galaxy S20+", subtype: "phone", width: 384, height: 854, dpr: 3.75, frame: "android", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-s20-ultra", name: "Galaxy S20 Ultra", subtype: "phone", width: 412, height: 915, dpr: 3.5, frame: "android", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-s20-fe", name: "Galaxy S20 FE", subtype: "phone", width: 412, height: 914, dpr: 2.625, frame: "android", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-s21", name: "Galaxy S21", subtype: "phone", width: 360, height: 800, dpr: 3, frame: "android", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-s21-plus", name: "Galaxy S21+", subtype: "phone", width: 384, height: 854, dpr: 3.75, frame: "android", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-s21-ultra", name: "Galaxy S21 Ultra", subtype: "phone", width: 384, height: 854, dpr: 3.75, frame: "android", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-s21-fe", name: "Galaxy S21 FE", subtype: "phone", width: 360, height: 800, dpr: 3, frame: "android", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-s22", name: "Galaxy S22", subtype: "phone", width: 360, height: 780, dpr: 3, frame: "android", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-s22-plus", name: "Galaxy S22+", subtype: "phone", width: 384, height: 854, dpr: 3.75, frame: "android", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-s22-ultra", name: "Galaxy S22 Ultra", subtype: "phone", width: 360, height: 772, dpr: 4, frame: "android", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-s23", name: "Galaxy S23", subtype: "phone", width: 360, height: 780, dpr: 3, frame: "android", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-s23-plus", name: "Galaxy S23+", subtype: "phone", width: 360, height: 780, dpr: 3, frame: "android", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-s23-ultra", name: "Galaxy S23 Ultra", subtype: "phone", width: 384, height: 824, dpr: 3.75, frame: "android", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-s23-fe", name: "Galaxy S23 FE", subtype: "phone", width: 360, height: 780, dpr: 3, frame: "android", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-s24", name: "Galaxy S24", subtype: "phone", width: 360, height: 780, dpr: 3, frame: "android", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-s24-plus", name: "Galaxy S24+", subtype: "phone", width: 384, height: 832, dpr: 3.5, frame: "android", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-s24-ultra", name: "Galaxy S24 Ultra", subtype: "phone", width: 384, height: 824, dpr: 3.75, frame: "android", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-s25", name: "Galaxy S25", subtype: "phone", width: 360, height: 780, dpr: 3, frame: "android", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-s25-plus", name: "Galaxy S25+", subtype: "phone", width: 412, height: 891, dpr: 3.5, frame: "android", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-s25-ultra", name: "Galaxy S25 Ultra", subtype: "phone", width: 412, height: 891, dpr: 3.5, frame: "android", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-note20", name: "Galaxy Note 20", subtype: "phone", width: 412, height: 915, dpr: 2.625, frame: "android", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-note20-ultra", name: "Galaxy Note 20 Ultra", subtype: "phone", width: 412, height: 883, dpr: 3.5, frame: "android", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-a52", name: "Galaxy A52", subtype: "phone", width: 412, height: 915, dpr: 2.625, frame: "android", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-a53", name: "Galaxy A53", subtype: "phone", width: 412, height: 915, dpr: 2.625, frame: "android", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-a54", name: "Galaxy A54", subtype: "phone", width: 412, height: 892, dpr: 2.625, frame: "android", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-a55", name: "Galaxy A55", subtype: "phone", width: 412, height: 892, dpr: 2.625, frame: "android", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-a14", name: "Galaxy A14", subtype: "phone", width: 360, height: 800, dpr: 3, frame: "android", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-a15", name: "Galaxy A15", subtype: "phone", width: 360, height: 800, dpr: 3, frame: "android", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-a16", name: "Galaxy A16", subtype: "phone", width: 360, height: 800, dpr: 3, frame: "android", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-z-fold2-cover", name: "Galaxy Z Fold2 (cover)", subtype: "foldable-cover", width: 360, height: 880, dpr: 2.625, frame: "android", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-z-fold2-open", name: "Galaxy Z Fold2 (unfolded)", subtype: "foldable-open", width: 884, height: 1104, dpr: 2, frame: "tablet", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-z-fold3-cover", name: "Galaxy Z Fold3 (cover)", subtype: "foldable-cover", width: 360, height: 832, dpr: 2.625, frame: "android", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-z-fold3-open", name: "Galaxy Z Fold3 (unfolded)", subtype: "foldable-open", width: 884, height: 1104, dpr: 2, frame: "tablet", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-z-fold4-cover", name: "Galaxy Z Fold4 (cover)", subtype: "foldable-cover", width: 360, height: 832, dpr: 2.625, frame: "android", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-z-fold4-open", name: "Galaxy Z Fold4 (unfolded)", subtype: "foldable-open", width: 906, height: 1080, dpr: 2, frame: "tablet", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-z-fold5-cover", name: "Galaxy Z Fold5 (cover)", subtype: "foldable-cover", width: 412, height: 882, dpr: 2.625, frame: "android", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-z-fold5-open", name: "Galaxy Z Fold5 (unfolded)", subtype: "foldable-open", width: 906, height: 1080, dpr: 2, frame: "tablet", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-z-fold6-cover", name: "Galaxy Z Fold6 (cover)", subtype: "foldable-cover", width: 360, height: 832, dpr: 2.625, frame: "android", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-z-fold6-open", name: "Galaxy Z Fold6 (unfolded)", subtype: "foldable-open", width: 928, height: 1080, dpr: 2, frame: "tablet", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-z-flip3-cover", name: "Galaxy Z Flip3 (cover)", subtype: "foldable-cover", width: 260, height: 512, dpr: 2, frame: "android", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-z-flip3-open", name: "Galaxy Z Flip3 (main)", subtype: "foldable-open", width: 360, height: 880, dpr: 3, frame: "tablet", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-z-flip4-cover", name: "Galaxy Z Flip4 (cover)", subtype: "foldable-cover", width: 260, height: 512, dpr: 2, frame: "android", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-z-flip4-open", name: "Galaxy Z Flip4 (main)", subtype: "foldable-open", width: 360, height: 880, dpr: 3, frame: "tablet", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-z-flip5-cover", name: "Galaxy Z Flip5 (cover)", subtype: "foldable-cover", width: 306, height: 318, dpr: 2.354, frame: "android", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-z-flip5-open", name: "Galaxy Z Flip5 (main)", subtype: "foldable-open", width: 360, height: 880, dpr: 3, frame: "tablet", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-z-flip6-cover", name: "Galaxy Z Flip6 (cover)", subtype: "foldable-cover", width: 306, height: 318, dpr: 2.354, frame: "android", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-z-flip6-open", name: "Galaxy Z Flip6 (main)", subtype: "foldable-open", width: 360, height: 880, dpr: 3, frame: "tablet", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-tab-s7", name: "Galaxy Tab S7", subtype: "tablet", width: 800, height: 1280, dpr: 2, frame: "tablet", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-tab-s8", name: "Galaxy Tab S8", subtype: "tablet", width: 800, height: 1280, dpr: 2, frame: "tablet", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-tab-s9", name: "Galaxy Tab S9", subtype: "tablet", width: 800, height: 1280, dpr: 2, frame: "tablet", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-tab-s9-ultra", name: "Galaxy Tab S9 Ultra", subtype: "tablet", width: 924, height: 1480, dpr: 2, frame: "tablet", userAgent: UA.android },
  { brand: "Samsung", id: "galaxy-tab-s10-plus", name: "Galaxy Tab S10+", subtype: "tablet", width: 825, height: 1320, dpr: 2, frame: "tablet", userAgent: UA.android },
  { brand: "Google", id: "pixel-4a", name: "Pixel 4a", subtype: "phone", width: 393, height: 851, dpr: 2.75, frame: "android-left", userAgent: UA.android },
  { brand: "Google", id: "pixel-5", name: "Pixel 5", subtype: "phone", width: 393, height: 851, dpr: 2.75, frame: "android-left", userAgent: UA.android },
  { brand: "Google", id: "pixel-5a", name: "Pixel 5a", subtype: "phone", width: 393, height: 851, dpr: 2.75, frame: "android-left", userAgent: UA.android },
  { brand: "Google", id: "pixel-6", name: "Pixel 6", subtype: "phone", width: 412, height: 915, dpr: 2.625, frame: "android", userAgent: UA.android },
  { brand: "Google", id: "pixel-6-pro", name: "Pixel 6 Pro", subtype: "phone", width: 412, height: 892, dpr: 3.5, frame: "android", userAgent: UA.android },
  { brand: "Google", id: "pixel-6a", name: "Pixel 6a", subtype: "phone", width: 412, height: 915, dpr: 2.625, frame: "android", userAgent: UA.android },
  { brand: "Google", id: "pixel-7", name: "Pixel 7", subtype: "phone", width: 412, height: 915, dpr: 2.625, frame: "android", userAgent: UA.android },
  { brand: "Google", id: "pixel-7-pro", name: "Pixel 7 Pro", subtype: "phone", width: 412, height: 892, dpr: 3.5, frame: "android", userAgent: UA.android },
  { brand: "Google", id: "pixel-7a", name: "Pixel 7a", subtype: "phone", width: 412, height: 915, dpr: 2.625, frame: "android", userAgent: UA.android },
  { brand: "Google", id: "pixel-8", name: "Pixel 8", subtype: "phone", width: 412, height: 915, dpr: 2.625, frame: "android", userAgent: UA.android },
  { brand: "Google", id: "pixel-8-pro", name: "Pixel 8 Pro", subtype: "phone", width: 448, height: 998, dpr: 3, frame: "android", userAgent: UA.android },
  { brand: "Google", id: "pixel-8a", name: "Pixel 8a", subtype: "phone", width: 412, height: 915, dpr: 2.625, frame: "android", userAgent: UA.android },
  { brand: "Google", id: "pixel-9", name: "Pixel 9", subtype: "phone", width: 360, height: 808, dpr: 3, frame: "android", userAgent: UA.android },
  { brand: "Google", id: "pixel-9-pro", name: "Pixel 9 Pro", subtype: "phone", width: 427, height: 952, dpr: 3, frame: "android", userAgent: UA.android },
  { brand: "Google", id: "pixel-9-pro-xl", name: "Pixel 9 Pro XL", subtype: "phone", width: 448, height: 997, dpr: 3, frame: "android", userAgent: UA.android },
  { brand: "Google", id: "pixel-9a", name: "Pixel 9a", subtype: "phone", width: 360, height: 808, dpr: 3, frame: "android", userAgent: UA.android },
  { brand: "Google", id: "pixel-fold-cover", name: "Pixel Fold (cover)", subtype: "foldable-cover", width: 360, height: 832, dpr: 3, frame: "android", userAgent: UA.android },
  { brand: "Google", id: "pixel-fold-open", name: "Pixel Fold (unfolded)", subtype: "foldable-open", width: 600, height: 729, dpr: 2.92, frame: "tablet", userAgent: UA.android },
  { brand: "Google", id: "pixel-9-pro-fold-cover", name: "Pixel 9 Pro Fold (cover)", subtype: "foldable-cover", width: 360, height: 808, dpr: 3, frame: "android", userAgent: UA.android },
  { brand: "Google", id: "pixel-9-pro-fold-open", name: "Pixel 9 Pro Fold (unfolded)", subtype: "foldable-open", width: 600, height: 690, dpr: 3, frame: "tablet", userAgent: UA.android },
  { brand: "OnePlus", id: "oneplus-8", name: "OnePlus 8", subtype: "phone", width: 412, height: 915, dpr: 2.625, frame: "android-left", userAgent: UA.android },
  { brand: "OnePlus", id: "oneplus-8-pro", name: "OnePlus 8 Pro", subtype: "phone", width: 412, height: 906, dpr: 3.5, frame: "android-left", userAgent: UA.android },
  { brand: "OnePlus", id: "oneplus-9", name: "OnePlus 9", subtype: "phone", width: 412, height: 915, dpr: 2.625, frame: "android-left", userAgent: UA.android },
  { brand: "OnePlus", id: "oneplus-9-pro", name: "OnePlus 9 Pro", subtype: "phone", width: 412, height: 919, dpr: 3.5, frame: "android-left", userAgent: UA.android },
  { brand: "OnePlus", id: "oneplus-10-pro", name: "OnePlus 10 Pro", subtype: "phone", width: 412, height: 919, dpr: 3.5, frame: "android-left", userAgent: UA.android },
  { brand: "OnePlus", id: "oneplus-11", name: "OnePlus 11", subtype: "phone", width: 412, height: 919, dpr: 3.5, frame: "android", userAgent: UA.android },
  { brand: "OnePlus", id: "oneplus-12", name: "OnePlus 12", subtype: "phone", width: 412, height: 905, dpr: 3.5, frame: "android", userAgent: UA.android },
  { brand: "OnePlus", id: "oneplus-13", name: "OnePlus 13", subtype: "phone", width: 412, height: 905, dpr: 3.5, frame: "android", userAgent: UA.android },
  { brand: "OnePlus", id: "oneplus-nord-2", name: "OnePlus Nord 2", subtype: "phone", width: 412, height: 915, dpr: 2.625, frame: "android-left", userAgent: UA.android },
  { brand: "OnePlus", id: "oneplus-nord-3", name: "OnePlus Nord 3", subtype: "phone", width: 412, height: 919, dpr: 3.5, frame: "android", userAgent: UA.android },
  { brand: "OnePlus", id: "oneplus-open-cover", name: "OnePlus Open (cover)", subtype: "foldable-cover", width: 414, height: 915, dpr: 2.7, frame: "android", userAgent: UA.android },
  { brand: "OnePlus", id: "oneplus-open-open", name: "OnePlus Open (unfolded)", subtype: "foldable-open", width: 840, height: 902, dpr: 2.7, frame: "tablet", userAgent: UA.android },
  { brand: "Nothing", id: "nothing-phone-1", name: "Nothing Phone (1)", subtype: "phone", width: 412, height: 915, dpr: 2.625, frame: "android-left", userAgent: UA.android },
  { brand: "Nothing", id: "nothing-phone-2", name: "Nothing Phone (2)", subtype: "phone", width: 412, height: 919, dpr: 2.625, frame: "android", userAgent: UA.android },
  { brand: "Nothing", id: "nothing-phone-2a", name: "Nothing Phone (2a)", subtype: "phone", width: 412, height: 915, dpr: 2.625, frame: "android", userAgent: UA.android },
  { brand: "Nothing", id: "nothing-phone-3a", name: "Nothing Phone (3a)", subtype: "phone", width: 412, height: 915, dpr: 2.625, frame: "android", userAgent: UA.android },
  { brand: "Xiaomi", id: "xiaomi-12", name: "Xiaomi 12", subtype: "phone", width: 360, height: 800, dpr: 3, frame: "android", userAgent: UA.android },
  { brand: "Xiaomi", id: "xiaomi-13", name: "Xiaomi 13", subtype: "phone", width: 360, height: 800, dpr: 3, frame: "android", userAgent: UA.android },
  { brand: "Xiaomi", id: "xiaomi-13-pro", name: "Xiaomi 13 Pro", subtype: "phone", width: 412, height: 916, dpr: 3.5, frame: "android", userAgent: UA.android },
  { brand: "Xiaomi", id: "xiaomi-14", name: "Xiaomi 14", subtype: "phone", width: 393, height: 873, dpr: 3, frame: "android", userAgent: UA.android },
  { brand: "Xiaomi", id: "xiaomi-14-pro", name: "Xiaomi 14 Pro", subtype: "phone", width: 412, height: 916, dpr: 3.5, frame: "android", userAgent: UA.android },
  { brand: "Xiaomi", id: "xiaomi-14-ultra", name: "Xiaomi 14 Ultra", subtype: "phone", width: 412, height: 916, dpr: 3.5, frame: "android", userAgent: UA.android },
  { brand: "Xiaomi", id: "xiaomi-15", name: "Xiaomi 15", subtype: "phone", width: 393, height: 873, dpr: 3, frame: "android", userAgent: UA.android },
  { brand: "Xiaomi", id: "xiaomi-15-pro", name: "Xiaomi 15 Pro", subtype: "phone", width: 412, height: 914, dpr: 3.5, frame: "android", userAgent: UA.android },
  { brand: "Redmi", id: "redmi-note-11", name: "Redmi Note 11", subtype: "phone", width: 393, height: 873, dpr: 2.75, frame: "android", userAgent: UA.android },
  { brand: "Redmi", id: "redmi-note-12", name: "Redmi Note 12", subtype: "phone", width: 393, height: 873, dpr: 2.75, frame: "android", userAgent: UA.android },
  { brand: "Redmi", id: "redmi-note-13", name: "Redmi Note 13", subtype: "phone", width: 393, height: 873, dpr: 2.75, frame: "android", userAgent: UA.android },
  { brand: "Redmi", id: "redmi-note-13-pro", name: "Redmi Note 13 Pro", subtype: "phone", width: 393, height: 873, dpr: 2.75, frame: "android", userAgent: UA.android },
  { brand: "Poco", id: "poco-f4", name: "Poco F4", subtype: "phone", width: 393, height: 873, dpr: 2.75, frame: "android", userAgent: UA.android },
  { brand: "Poco", id: "poco-f5", name: "Poco F5", subtype: "phone", width: 393, height: 873, dpr: 2.75, frame: "android", userAgent: UA.android },
  { brand: "Poco", id: "poco-f6", name: "Poco F6", subtype: "phone", width: 412, height: 914, dpr: 3, frame: "android", userAgent: UA.android },
  { brand: "Poco", id: "poco-x5", name: "Poco X5", subtype: "phone", width: 393, height: 873, dpr: 2.75, frame: "android", userAgent: UA.android },
  { brand: "Poco", id: "poco-x6", name: "Poco X6", subtype: "phone", width: 412, height: 914, dpr: 3, frame: "android", userAgent: UA.android },
  { brand: "Poco", id: "poco-x6-pro", name: "Poco X6 Pro", subtype: "phone", width: 412, height: 914, dpr: 3, frame: "android", userAgent: UA.android },
  { brand: "Motorola", id: "motorola-edge-30", name: "Motorola Edge 30", subtype: "phone", width: 393, height: 873, dpr: 2.75, frame: "android", userAgent: UA.android },
  { brand: "Motorola", id: "motorola-edge-40", name: "Motorola Edge 40", subtype: "phone", width: 384, height: 854, dpr: 2.8125, frame: "android", userAgent: UA.android },
  { brand: "Motorola", id: "motorola-edge-50-pro", name: "Motorola Edge 50 Pro", subtype: "phone", width: 412, height: 914, dpr: 3, frame: "android", userAgent: UA.android },
  { brand: "Motorola", id: "motorola-razr-40-cover", name: "Motorola razr 40 (cover)", subtype: "foldable-cover", width: 174, height: 175, dpr: 3, frame: "android", userAgent: UA.android },
  { brand: "Motorola", id: "motorola-razr-40-open", name: "Motorola razr 40 (unfolded)", subtype: "foldable-open", width: 412, height: 1008, dpr: 2.625, frame: "tablet", userAgent: UA.android },
  { brand: "Motorola", id: "motorola-razr-2024-cover", name: "Motorola razr 2024 (cover)", subtype: "foldable-cover", width: 180, height: 180, dpr: 3, frame: "android", userAgent: UA.android },
  { brand: "Motorola", id: "motorola-razr-2024-open", name: "Motorola razr 2024 (unfolded)", subtype: "foldable-open", width: 412, height: 1008, dpr: 2.625, frame: "tablet", userAgent: UA.android },
  { brand: "Oppo", id: "oppo-find-x5-pro", name: "Oppo Find X5 Pro", subtype: "phone", width: 360, height: 804, dpr: 3.5, frame: "android", userAgent: UA.android },
  { brand: "Oppo", id: "oppo-find-x6-pro", name: "Oppo Find X6 Pro", subtype: "phone", width: 412, height: 919, dpr: 3.5, frame: "android", userAgent: UA.android },
  { brand: "Oppo", id: "oppo-find-x7-ultra", name: "Oppo Find X7 Ultra", subtype: "phone", width: 412, height: 919, dpr: 3.5, frame: "android", userAgent: UA.android },
  { brand: "Oppo", id: "oppo-reno-10", name: "Oppo Reno 10", subtype: "phone", width: 393, height: 873, dpr: 2.75, frame: "android", userAgent: UA.android },
  { brand: "Oppo", id: "oppo-reno-11", name: "Oppo Reno 11", subtype: "phone", width: 393, height: 873, dpr: 2.75, frame: "android", userAgent: UA.android },
  { brand: "Vivo", id: "vivo-x90-pro", name: "Vivo X90 Pro", subtype: "phone", width: 392, height: 870, dpr: 3.2, frame: "android", userAgent: UA.android },
  { brand: "Vivo", id: "vivo-x100-pro", name: "Vivo X100 Pro", subtype: "phone", width: 392, height: 870, dpr: 3.2, frame: "android", userAgent: UA.android },
  { brand: "Honor", id: "honor-magic-5-pro", name: "Honor Magic 5 Pro", subtype: "phone", width: 397, height: 858, dpr: 3.3, frame: "android", userAgent: UA.android },
  { brand: "Honor", id: "honor-magic-6-pro", name: "Honor Magic 6 Pro", subtype: "phone", width: 412, height: 902, dpr: 3.1, frame: "android", userAgent: UA.android },
  { brand: "Honor", id: "honor-magic-v2-cover", name: "Honor Magic V2 (cover)", subtype: "foldable-cover", width: 391, height: 876, dpr: 2.7, frame: "android", userAgent: UA.android },
  { brand: "Honor", id: "honor-magic-v2-open", name: "Honor Magic V2 (unfolded)", subtype: "foldable-open", width: 738, height: 827, dpr: 2.4, frame: "tablet", userAgent: UA.android },
  { brand: "Asus", id: "asus-rog-phone-6", name: "Asus ROG Phone 6", subtype: "phone", width: 393, height: 873, dpr: 2.75, frame: "android-plain", userAgent: UA.android },
  { brand: "Asus", id: "asus-rog-phone-7", name: "Asus ROG Phone 7", subtype: "phone", width: 393, height: 873, dpr: 2.75, frame: "android-plain", userAgent: UA.android },
  { brand: "Asus", id: "asus-rog-phone-8", name: "Asus ROG Phone 8", subtype: "phone", width: 393, height: 873, dpr: 2.75, frame: "android", userAgent: UA.android },
  { brand: "Asus", id: "asus-zenfone-9", name: "Asus Zenfone 9", subtype: "phone", width: 360, height: 800, dpr: 3, frame: "android-left", userAgent: UA.android },
  { brand: "Asus", id: "asus-zenfone-10", name: "Asus Zenfone 10", subtype: "phone", width: 360, height: 800, dpr: 3, frame: "android-left", userAgent: UA.android },
  { brand: "Desktop", id: "laptop", name: "Laptop", subtype: "desktop", width: 1280, height: 800, dpr: 1, frame: "none", userAgent: UA.desktop },
  { brand: "Desktop", id: "laptop-l", name: "Laptop L", subtype: "desktop", width: 1440, height: 900, dpr: 1, frame: "none", userAgent: UA.desktop },
  { brand: "Desktop", id: "desktop-fhd", name: "Desktop 1080p", subtype: "desktop", width: 1920, height: 1080, dpr: 1, frame: "none", userAgent: UA.desktop },
  { brand: "Desktop", id: "desktop-qhd", name: "Desktop 1440p", subtype: "desktop", width: 2560, height: 1440, dpr: 1, frame: "none", userAgent: UA.desktop },
  { brand: "Custom", id: "custom", name: "Custom (W x H)", subtype: "phone", width: 400, height: 800, dpr: 3, frame: "android", userAgent: UA.android },
];
